spring:
  application:
    name: emailservice
  rabbitmq:
    username: quickmicroservice
    password: quickmicroservice
    port: '5672'
    host: localhost
  mail:
    host: localhost
  config:
    import: "optional:configserver:http://localhost:8080"
server:
  port: 8083
management:
  tracing:
    sampling:
      probability: 1.0


ms:
  rabbit:
    exchange:
      name: quickexchange
    queue:
      name: quickqueue
    routing:
      name: quickrouting

